### PR TITLE
Use the major mode's syntax table directly.

### PR DESCRIPTION
**Pull request by Fanael**
So far, we assumed that `[]` `()` `{}` are always the delimiters, and the only delimiters, we want to highlight. But this is not true. For example, in Pascal, `{}` are comment delimiters, and in C++, `<>` serve as brackets in template syntax. The respective major modes get this right, we don't, so rely on them. Code simplification is an added benefit.

Note: currently it's probably buggy and certainly incomplete. For example, it doesn't respect `rainbow-delimiters-highlight-TYPE-p` yet.

### CODE REVIEW

**Comment by Fanael** [comment]
@purcell: do you have any idea how to generalize `rainbow-delimiters-highlight-TYPE-p` to deal with arbitrary characters? I don't want to merge this branch until it reaches feature parity, even if I consider the feature misguided and googling shows that nobody is using it.

**Comment by purcell** [comment]
Can you just extend the `cond` in `rainbow-delimiters--char-ineligible-p`? ie. consider `(` and `)` ineligible unless `rainbow-delimiters-highlight-parens-p` etc?

**Comment by Fanael** [comment]
This is not what I have in mind, this is already [being handled in `rainbow-delimiters--apply-color`](https://github.com/jlr/rainbow-delimiters/blob/2cde18809f7bb9d5c75a0b6bf893c81c2875d98e/rainbow-delimiters.el#L437).

What I have no idea how to handle is toggling the highlighting of other characters that are delimiters according to the major mode, such as `<` and `>` (sometimes) in `c++-mode` or `a` and `b` in `hell-mode`¹. Because it's the major mode who decides what is and what is not a delimiters, the delimiters can, in theory, be arbitrary characters, so we ought to give the user a switch generic enough to handle anything. The problem is I have no idea what that switch should look like.

By the way, scratch my comment about nobody using this feature. Github search reveals that there are, in fact, several users.

---
1. That is, a major mode that violates as many common assumptions as possible while still being, in principle, a well-behaved major mode. It's a useful thought experiment, because it always turns out there's a code out there somewhere that, in some respects, does something very outlandish while being correct.

**Comment by purcell** [comment]
Hmm. So maybe some sort of customizable whitelist look-up table of pairs to highlight? Or a blacklist?

**Comment by Fanael** [comment]
Something like this?

``` emacs-lisp
(defvar blacklist '(?\( ?\) ?\[ ?\]))
```

I think it would work.

**Comment by Fanael** [comment]
Ready for dogfooding.

@purcell, can you install it locally?

**Comment by Fanael** [comment]
I'm starting to like the way the code looks now. Apart from `rainbow-delimiters--syntax-ppss`, everything is so simple. Now, if only I could find a way to get rid of that, too…

**Comment by purcell** [comment]
> everything is so simple

That's always a good sign.

I'll give this a whirl over the next few days, then.

**Comment by Fanael** [comment]
I think that this change, especially when merged with the `use-syntax-ppss` branch, warrants a version bump to 1.4 or even 2.0, would you agree?

**Comment by purcell** [comment]
> warrants a version bump to 1.4 or even 2.0

Yes. If the public API is preserved, I'd probably go with 1.4. Otherwise 2.0.

**Comment by Fanael** [comment]
It's not. `rainbow-delimiters-delimiter-blacklist` replaces `rainbow-delimiters-highlight-TYPE-p`. 2.0 it is, then.

**Comment by purcell** [comment]
:+1:

**Comment by Fanael** [comment]
By the way, I gave you collaborator access to the [new repo](https://github.com/Fanael/rainbow-delimiters). `rainbow-delimiters` needs a proper test suite and continuous integration, but I can't set up Travis here, so we'll be moving after the two outstanding pull requests are dealt with.

**Comment by purcell** [comment]
Sounds good. Let me know when the switch is official, so we can update the MELPA recipe.

**Comment by Fanael** [comment]
I think I migrated everything apart from bug reports.

I merged both branches, because they pass the shiny, new test suite¹, while the old master doesn't.

I think we're ready for the switch. I'll just leave a note in the bug reports still open reminding the reporter to report the issue again at the new address.

# 
1. The test suite needs some love, though. Its code is quite hacky in a few places.

**Pull request closed without merging**
