### PR TITLE
Don't enable in reftex-toc-mode

### PR DESCRIPTION
**Pull request by swsnr**
See #31

### CODE REVIEW

**Comment by swsnr** [comment]
`completion-list-mode` should be added as well.

**Comment by swsnr** [comment]
Likewise, `reftex-select-label-mode`.

Sorry, I was a bit eager in opening this PR, and should have invested more thoroughly.

**Comment by purcell** [comment]
No probs. Maybe amend the commit and force-push it, then ping us when done. But also note #33, which says that if upstream fixes are feasible, they'd be preferable to excluding further modes here.

**Comment by swsnr** [comment]
@purcell I amended the PR. 

I'd have reported this upstream, but all of these modes are built-in.  They should probably inherit `special-mode`, but even if the Emacs developers agree with us, it'll take ages for such a change to appear in a stable Emacs release, so I did not bother to `M-x report-emacs-bug`, and instead opened this PR.

**Comment by purcell** [comment]
Okay, great - thanks!

**Comment by Fanael** [comment]
Please report to the upstream as well. I can't guarantee I'm going to tolerate this hack forever and that I'm not going to just ignore broken upstreams and set this variable `nil` at some point.

> even if the Emacs developers agree with us

I wouldn't worry too much about that. They already fixed this exact bug (namely, using `face` instead of `font-lock-face`) in eshell and rcirc.

**Comment by purcell** [comment]
I've just been doing the same thing over in `haskell-interactive-mode`... :-)

**Comment by swsnr** [comment]
@Fanael Ok, will do.

**Comment by swsnr** [comment]
@Fanael @purcell See http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18496 and http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18497

**Pull request merged**
