### PR TITLE
fix/hack to play nicely with org-mode

### PR DESCRIPTION
**Pull request by defanor**
don't add font-lock-face if face is already added

### CODE REVIEW

**Comment by defanor** [comment]
I am not sure if it is the proper way to fix that issue (https://github.com/jlr/rainbow-delimiters/issues/10), but it works for me.

**Comment by Fanael** [comment]
Could you file this pull request to [my repo](https://github.com/Fanael/rainbow-delimiters), too? I'm seriously thinking about taking over the maintenance of the package.

**Comment by defanor** [comment]
I'd like to, but I'm new to github, and not sure how to do it. Will try.

**Comment by Fanael** [comment]
Not needed anymore because of b3f87cfe.

**Pull request closed without merging**
