### PR TITLE
Use the syntax table to determine if a delimiters starts a comment.

### PR DESCRIPTION
**Pull request by Fanael**
@purcell: can you help me with testing this change by using it and seeing if anything breaks?

### CODE REVIEW

**Comment by purcell** [comment]
Have installed locally. Will let you know if I see any probs.

**Comment by Fanael** [comment]
Note: this change probably doesn't look like it, but it's the first step in changing rainbow-delimiters so it uses the major mode's syntax table directly, without modifications. This will bring us proper handling of, say, the square brackets in C++ template syntax, for free. That's a pretty big change, though, so I'd rather do it gradually.

**Comment by Fanael** [comment]
I take it this means you noticed no problems yet?

**Comment by purcell** [comment]
No, but I haven't really been coding a lot.

My advice would be to go ahead and commit this work to master so that you get more feedback. Then when you're happy it's all working well, tag a fresh version.

**Comment by Fanael** [comment]
> My advice would be to go ahead and commit this work to master so that you get more feedback. Then when you're happy it's all working well, tag a fresh version.

Yeah, that's what I'm going to do. Just asking in case you found anything.

**Pull request merged**
